services:
  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-database
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - "./.env"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
