name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          # Skip hostname verification since we're having DNS issues
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      - name: SSH and deploy
        run: |
          # Use the IP address directly from the secrets
          ssh -i ~/.ssh/private_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} '
            cd /home/ubuntu/graphql-ecommerce-backend && 
            echo "PORT=${{ secrets.PORT }}" > .env && 
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env && 
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env && 
            pnpm install && 
            pnpm build && 
            npx prisma generate && 
            npx prisma migrate deploy && 
            pm2 restart all || pm2 start dist/server.js --name app
          '
